server:
  port: 8088 #服务端口
spring:
  application:
    name:  microservice-config-server #指定服务名
  profiles:
    active: git #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
#    active: subversion #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
#    active: native     #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://gitee.com/wangth3/springcloudconfig.git
#          search-paths:
#          - myspringcloudconfig		#配置文件目录地址
          username: 17854117835	#码云账号（公有项目不需要设置）
          password: li19980418 	#码云密码（公有项目不需要设置）
###          如下是SVN配置
#        svn:
#          uri: http://svnhost:port/svn/app-config #SVN仓库地址
#          username: wangth_oup
#          password:
#          default-label: trunk #默认SVN分支
###          如下是本地配置
#        native:
#          search-locations: classpath:/configs #配置文件存放的目录
      label: master	#分支名称
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:9100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.application.name}###${server.port} #指定实例id