server:
  port: 8083
myspcloud:
  item:
    url: http://127.0.0.1:8082/item/
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
  application:
    name: app-order
###服务注册到eureka注册中心的地址
#服务注册到有认证需求的注册中心时，需要设置如下地址：http://USER:PASSWORD@127.0.0.1:端口号/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:9100/eureka
#      defaultZone: http://wangth:wangth3@127.0.0.1:8100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id
#Ribbon负载均衡
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启hystrix断路器
feign:
  hystrix:
    enabled: true
#配置Swagger接口扫描范围
swagger:
  base-package: com.ritian.order